spring.datasource.url=jdbc:postgresql://dpg-d6jb2824d50c73ejd3a0-a:5432/dam_cloud_db
spring.datasource.username=dam_cloud_db_user
spring.datasource.password=O0oWfZtDUf4EFdLAO2UWf3PaHhjOYkIa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect