# PORT dinàmic cloud
server.port=${PORT:5432}

# Database cloud variables
# Use an empty default to avoid unresolved placeholder errors when DB env vars aren't set during build
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect